pcj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView

from finance.views import finance_view

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('finance/', include('finance.urls')),
    path('news/', include('news.urls')),
    path('', include('page.urls')),
    path('product/', include('product.urls')),
    path('project/', include('project.urls')),

    path('webmail/', RedirectView.as_view(url='https://www.pcjindustries.co.th:2096/')),
    path('whm/', RedirectView.as_view(url='https://www.pcjindustries.co.th:2087/')),

    # legacy path for this url 'index.php?tpid=0031&pgname=finance&count=1'
    path('index.php/', finance_view, name='finance-view-2'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import (
    list_fire_door,
    list_fire_damper,
    list_fsd_ul,
    list_other_damper,
    list_duct_silencer,
    list_air_outlet,
)

app_name = 'product'
urlpatterns = [
    path('fire-steel-door', list_fire_door, name='product-frd'),
    path('fire-damper', list_fire_damper, name='product-fdc'),
    # path('fsd-ul', list_fsd_ul, name='product-fsd-ul'),
    path('duct-damper', list_other_damper, name='product-ddp'),
    path('duct-silencer', list_duct_silencer, name='product-ds'),
    path('air-outlet', list_air_outlet, name='product-aol'),
]

project/urls.py
from django.urls import path
from .views import (
    ProjectListView,
    project_detail,
)

app_name = 'project'
urlpatterns = [
    path('', ProjectListView.as_view(), name='project-list'),
    path('<int:id>/', project_detail, name='project-detail'),
]

page/templates/page/page_about.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <video controls class="img-fluid" poster="{{MEDIA_URL|add:'videos/pcj_about_us_03_intro.jpg'}}">
                    <source src="{{MEDIA_URL|add:'videos/pcj_about_us_03_intro.mp4'}}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        </div>
        <br>

        <h3 class="text-center text-capitalize">{% trans 'about-us' %}</h3>

        <div class="row justify-content-center">
            <div class="col-lg-6 text-justify">
                {% trans 'about-us-content-1' %}
            </div>
        </div>

        <br>
        <div class="text-center">
            <img src="{% static 'images/certificate.jpg' %}" class="img-fluid">
        </div>
        <br>

        <div class="row justify-content-center">
            <div class="col-lg-6 text-justify">
                {% trans 'about-us-content-2' %}
            </div>
        </div>

        <br>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <img src="{% static 'images/map_world.jpg' %}" class="img-fluid">
            </div>
        </div>
        <br>
        <br>

        <div class="row img-factory">
            {% for img in factory_images %}
                {% if forloop.first %}
                    <div class="col-md-12">
                        <img src="{% static img %}" class="img-fluid">
                    </div>
                {% else %}
                    <div class="col-md-6">
                        <img src="{% static img %}" class="img-fluid">
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

page/templates/page/page_career.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    <br>
    <div class="container">
        <h3 class="text-center text-capitalize">{% trans 'career' %}</h3>

        <div class="row justify-content-center">
            <div class="col-lg-6 text-justify">
                <p>
                    {% trans 'career-content-1' %}
                    <span class="email-career">
                        <span class="icon-envelope"></span> <a href="mailto:{{EMAIL_CAREER}}">{{EMAIL_CAREER}}</a>
                    </span>
                    {% trans 'career-content-2' %}
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="contact-card">
                    <h3 class="text-uppercase">{% trans 'pcj-industries-full' %}</h3>
                    <h3 class="text-uppercase">({% trans 'headquarters' %})</h3>
                    <br>
                    <p>
                        {% trans 'pcj-office-road' %}<br>
                        {% trans 'pcj-office-area' %}<br>
                        {% trans 'pcj-office-province' %}<br>
                        {% trans 'pcj-office-work-hour' %}
                    </p>

                    <p>
                        <span class="icon-phone-alt"></span>&nbsp;
                        {% if LANG == 'en' %}
                            <a href="tel:{{PHONE1_en}}">{{PHONE1_en}}</a>,&nbsp;
                            <a href="tel:{{PHONE2_en}}">{{PHONE2_en}}</a>
                        {% else %}
                            <a href="tel:{{PHONE1_th}}">{{PHONE1_th}}</a>,&nbsp;
                            <a href="tel:{{PHONE2_th}}">{{PHONE2_th}}</a>
                        {% endif %}
                        <br>
                    </p>
                </div>
            </div>
            <div class="col-md-7 map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d242.17815034861803!2d100.55958969822574!3d13.787890070907615!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30e29c3900acb641%3A0x9bc8d88eddc2c0e8!2z4Lia4Lij4Li04Lip4Lix4LiXIOC4nuC4teC4i-C4teC5gOC4iCDguK3guLjguJXguKrguLLguKvguIHguKPguKPguKEg4LiI4Liz4LiB4Lix4LiU!5e0!3m2!1sen!2sus!4v1562645964776!5m2!1sen!2sus"></iframe>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h5 class="text-center">{% trans 'job-positions-available' %}</h5>
                <div class="row">
                    <div class="col-md-6">
                        <ul style="margin-bottom: 0">
                            <li>{% trans 'Sales Executive(lnternational)' %}</li>
                            <li>{% trans 'Sales Executive(Domestic)' %}</li>
                            <li>{% trans 'Sales Coordinator' %}</li>
                            <li>{% trans 'Marketing Executive' %}</li>
                            <li>{% trans 'Purchasing Admin.' %}</li>
                            <li>{% trans 'Accountant' %}</li>
                            <li>{% trans 'Finance Staff' %}</li>
                            <li>{% trans 'HR Admin.' %}</li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul>
                            <li>{% trans 'Production Engineer' %}</li>
                            <li>{% trans 'R&D Engineer' %}</li>
                            <li>{% trans 'QA Engineer' %}</li>
                            <li>{% trans 'Construction & Maintenance Engineer' %}</li>
                            <li>{% trans 'CAD Operator' %}</li>
                            <li>{% trans 'Operator/Technician' %}</li>
                            <li>{% trans 'Warehouse Admin.' %}</li>
                            <li>{% trans 'Production Admin.' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

page/templates/page/page_contact.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    <br>
    <div class="container">
        <h3 class="text-center text-capitalize">{% trans 'contact-us' %}</h3>
        <br>

        <div class="row">
            <div class="col-md-5">
                <div class="contact-card">
                    <h3 class="text-uppercase">{% trans 'pcj-industries-full' %}</h3>
                    <h3 class="text-uppercase">({% trans 'headquarters' %})</h3>
                    <br>
                    <p>
                        {% trans 'pcj-office-road' %}<br>
                        {% trans 'pcj-office-area' %}<br>
                        {% trans 'pcj-office-province' %}<br>
                        {% trans 'pcj-office-work-hour' %}
                    </p>

                    <p>
                        <span class="icon-phone-alt"></span>&nbsp;
                        {% if LANG == 'en' %}
                            <a href="tel:{{PHONE1_en}}">{{PHONE1_en}}</a>,&nbsp;
                            <a href="tel:{{PHONE2_en}}">{{PHONE2_en}}</a>
                        {% else %}
                            <a href="tel:{{PHONE1_th}}">{{PHONE1_th}}</a>,&nbsp;
                            <a href="tel:{{PHONE2_th}}">{{PHONE2_th}}</a>
                        {% endif %}
                        <br>
                        <span class="icon-envelope"></span>&nbsp;
                        <a href="mailto:{{EMAIL_SALES}}">{{EMAIL_SALES}}</a>
                    </p>
                </div>
            </div>
            <div class="col-md-7 map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d242.17815034861803!2d100.55958969822574!3d13.787890070907615!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30e29c3900acb641%3A0x9bc8d88eddc2c0e8!2z4Lia4Lij4Li04Lip4Lix4LiXIOC4nuC4teC4i-C4teC5gOC4iCDguK3guLjguJXguKrguLLguKvguIHguKPguKPguKEg4LiI4Liz4LiB4Lix4LiU!5e0!3m2!1sen!2sus!4v1562645964776!5m2!1sen!2sus"></iframe>
            </div>
        </div>

        <div class="row">
            <div class="col-md-5">
                <div class="contact-card">
                    <h3 class="text-uppercase">{% trans 'factory' %}</h3>
                    <br>
                    <p>
                        {% trans 'pcj-factory-road' %}<br>
                        {% trans 'pcj-factory-area' %}<br>
                        {% trans 'pcj-factory-province' %}<br>
                        {% trans 'pcj-factory-work-hour' %}
                    </p>
                    <p>
                        <span class="icon-phone-alt"></span>&nbsp;
                        {% if LANG == 'en' %}
                            <a href="tel:{{PHONE_FACTORY_en}}">{{PHONE_FACTORY_en}}</a>
                        {% else %}
                            <a href="tel:{{PHONE_FACTORY_th}}">{{PHONE_FACTORY_th}}</a>
                        {% endif %}
                        <br>
                        <span class="icon-envelope"></span>&nbsp;
                        <a href="mailto:{{EMAIL_SALES}}">{{EMAIL_SALES}}</a>
                    </p>
                </div>
            </div>
            <div class="col-md-7 map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3860.7119250116843!2d101.01420212434525!3d14.615479504509283!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x311ddd1af4ee16c1%3A0xd3f0ffd50ee206fd!2sPCJ+Industry+Co.%2C+Ltd.!5e0!3m2!1sen!2s!4v1469268505549"></iframe>
            </div>
        </div>
    </div>
{% endblock content %}

page/templates/page/page_home.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}

    <div class="container-fluid">
        <div class="row exhibition">
            <div class="col-12 align-self-center text-center">
                <img src="{% static 'images/intersec_dubai_2025_banner.jpg' %}" alt="Intersec Dubai 2025 banner">
            </div>
        </div>
    </div>
    
    <div class="container-fluid">
        <div class="row intro">
            <div class="col-md-5 align-self-center text-center text-md-right">
                <img src="{% static 'images/pcj-logo.png' %}" alt="pcj brand logo">
            </div>
            <div class="col-md-7 col-lg-5 align-self-center">
                <h1 class="text-center text-md-left">{% trans 'home-intro-header' %}</h1>
                <p>{% trans 'home-intro-content' %}</p>
            </div>

        </div>
    </div>
    <br>

    <div class="container">
        <div class="intro-video">
            <div class="row product-home black">
                <div class="col-lg-10 offset-lg-1">
                    <video controls class="img-fluid" poster="{{MEDIA_URL|add:'videos/PCJ_door_2024_'|add:LANG|add:'.jpg'}}">
                        <source src="{{MEDIA_URL|add:'videos/PCJ_door_2024_'|add:LANG|add:'.mp4'}}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row product-home csd">
            <div class="col-lg-6">
                <br>
                <h1 class="text-center">{% trans 'home-frd-header' %}</h1>
                <hr>
                <section>
                    {% trans 'home-frd-content' %}
                    <div class="text-center">
                        <a href="{% url 'product:product-frd'%}" class="btn btn-outline-primary text-capitalize">{% trans 'more-details' %}</a>
                    </div>
                </section>
            </div>
            <div class="col-lg-6 align-self-center">
                <div class="row justify-content-center">
                    <div class="frame"><img src="{% static 'images/product/csd/d01.jpg' %}" alt="red fire steel door with vision"></div>
                    <div class="frame"><img src="{% static 'images/product/csd/d02.jpg' %}" alt="white fire steel door"></div>
                    <div class="frame"><img src="{% static 'images/product/csd/d03.jpg' %}" alt="blue fire steel door"></div>
                </div>
                <div class="row justify-content-center">
                    <div class="frame"><img src="{% static 'images/product/csd/d04.jpg' %}" alt="oak fire steel door"></div>
                    <div class="frame"><img src="{% static 'images/product/csd/d05.jpg' %}" alt="maple fire steel door"></div>
                    <div class="frame"><img src="{% static 'images/product/csd/d06.jpg' %}" alt="golden teak fire steel door"></div>
                </div>
            </div>
        </div>

        <div class="row product-home fdc">
            <div class="col-lg-6">
                <br>
                <h1 class="text-center">{% trans 'home-fdc-header' %}</h1>
                <hr>
                <section>
                    {% trans 'home-fdc-content' %}
                    <div class="text-center">
                        <a href="{% url 'product:product-fdc'%}" class="btn btn-outline-primary text-capitalize">{% trans 'more-details' %}</a>
                    </div>
                </section>
            </div>
            <div class="col-lg-6 align-self-center">
                <div class="row justify-content-center">
                    <div class="frame long"><img src="{% static 'images/product/fdc/fdc-in.jpg' %}" alt="fire damper in airstream"></div>
                    <div class="frame long"><img src="{% static 'images/product/fdc/fdc-out.jpg' %}" alt="fire damper out of airstream"></div>
                    <div class="frame long"><img src="{% static 'images/product/fdc/fdc-multi.jpg' %}" alt="fire damper multiple section"></div>
                </div>
            </div>
        </div>

        <div class="row product-home ddp">
            <div class="col-lg-6">
                <br>
                <h1 class="text-center">{% trans 'home-ddp-header' %}</h1>
                <hr>
                <section>
                    {% trans 'home-ddp-content' %}
                    <div class="text-center">
                        <a href="{% url 'product:product-ddp'%}" class="btn btn-outline-primary text-capitalize">{% trans 'more-details' %}</a>
                    </div>
                </section>
            </div>
            <div class="col-lg-6 align-self-center">
                <div class="row justify-content-center">
                    <div class="frame"><img src="{% static 'images/product/ddp/vl.jpg' %}" alt="volume damper"></div>
                    <div class="frame"><img src="{% static 'images/product/ddp/md.jpg' %}" alt="motorized damper"></div>
                    <div class="frame"><img src="{% static 'images/product/ddp/ovd.jpg' %}" alt="flat oval volume damper"></div>
                </div>
                <div class="row justify-content-center">
                    <div class="frame"><img src="{% static 'images/product/ddp/rml.jpg' %}" alt="round motorized damper"></div>
                    <div class="frame"><img src="{% static 'images/product/ddp/gd.jpg' %}" alt="gravity damper"></div>
                    <div class="frame"><img src="{% static 'images/product/ddp/rd.jpg' %}" alt="relief damper"></div>
                </div>
            </div>
        </div>

        <div class="row product-home ds">
            <div class="col-lg-6">
                <br>
                <h1 class="text-center">{% trans 'home-ds-header' %}</h1>
                <hr>
                <section>
                    {% trans 'home-ds-content' %}
                    <div class="text-center">
                        <a href="{% url 'product:product-ds'%}" class="btn btn-outline-primary text-capitalize">{% trans 'more-details' %}</a>
                    </div>
                </section>
            </div>
            <div class="col-lg-6 align-self-center">
                <div class="row justify-content-center">
                    <div class="frame long"><img src="{% static 'images/product/ds/ds.jpg' %}" alt="duct silencer"></div>
                    <div class="frame long"><img src="{% static 'images/product/ds/rds.jpg' %}" alt="round duct silencer"></div>
                    <div class="frame long"><img src="{% static 'images/product/ds/acl.jpg' %}" alt="acoustic louver"></div>
                </div>
            </div>
        </div>

        <div class="row product-home aol">
            <div class="col-lg-6">
                <br>
                <h1 class="text-center">{% trans 'home-aol-header' %}</h1>
                <hr>
                <section>
                    {% trans 'home-aol-content' %}
                    <div class="text-center">
                        <a href="{% url 'product:product-aol'%}" class="btn btn-outline-primary text-capitalize">{% trans 'more-details' %}</a>
                    </div>
                </section>
            </div>
            <div class="col-lg-6 align-self-center">
                <div class="row justify-content-center">
                    <div class="frame long"><img src="{% static 'images/product/aol/scd.jpg' %}" alt="squaure ceiling diffuser"></div>
                    <div class="frame long"><img src="{% static 'images/product/aol/egh.jpg' %}" alt="egg crate grille"></div>
                    <div class="frame long"><img src="{% static 'images/product/aol/af2.jpg' %}" alt="aluminum filter"></div>
                </div>
                <div class="row justify-content-center">
                    <div class="frame long"><img src="{% static 'images/product/aol/obv.jpg' %}" alt="opposed blade volume damper"></div>
                    <div class="frame long"><img src="{% static 'images/product/aol/rnd.jpg' %}" alt="round ceiling diffuser"></div>
                    <div class="frame long"><img src="{% static 'images/product/aol/agt.jpg' %}" alt="air grille"></div>
                </div>
            </div>
        </div>
        <hr>

        <h3 class="text-center text-capitalize">{% trans 'projects' %}</h3>
        {% include 'project/row_project.html' %}
        <div class="text-center">
            <a href="{% url 'project:project-list' %}" class="btn btn-outline-primary text-capitalize">{% trans 'view-all-projects' %}</a>
        </div>

    </div>
{% endblock content %}

{% block extra_js %}
    <script src="{% static 'js/projectModal.js' %}"></script>
{% endblock extra_js %}