news/urls.py
from django.urls import path
from .views import (
    NewsListView,
    news_detail,
)

app_name = 'news'
urlpatterns = [
    path('', NewsListView.as_view(), name='news-list'),
    path('<int:id>/', news_detail, name='news-detail'),
]

pcj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView

from finance.views import finance_view

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('finance/', include('finance.urls')),
    path('news/', include('news.urls')),
    path('', include('page.urls')),
    path('product/', include('product.urls')),
    path('project/', include('project.urls')),

    path('webmail/', RedirectView.as_view(url='https://www.pcjindustries.co.th:2096/')),
    path('whm/', RedirectView.as_view(url='https://www.pcjindustries.co.th:2087/')),

    # legacy path for this url 'index.php?tpid=0031&pgname=finance&count=1'
    path('index.php/', finance_view, name='finance-view-2'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.template.defaultfilters import truncatechars, striptags
from django.db.models import Max
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import get_language

# Create your models here.
class News(models.Model):
    title_en    = models.TextField(verbose_name='title english')
    title_th    = models.TextField(blank=True, verbose_name='title thai')
    content_en  = RichTextUploadingField(verbose_name='content english')
    content_th  = RichTextUploadingField(default='', blank=True, verbose_name='content thai')
    image       = models.ImageField(upload_to='news')
    order       = models.PositiveIntegerField(default=0, blank=False, null=False)
    publish     = models.BooleanField(default=False)

    class Meta:
        ordering = ('-order',)
        verbose_name_plural = "news"

    def __str__(self):
        return self.short_title_en

    @property
    def short_title_en(self):
        return truncatechars(self.title_en, 30)
    @property
    def short_content_en(self):
        return truncatechars(striptags(self.content_en), 50)

    @property
    def title(self):
        return self.title_th if get_language()=='th' and self.title_th else self.title_en

    @property
    def content(self):
        return self.content_th if get_language()=='th' and self.content_th else self.content_en

    @property
    def title_short(self):
        return truncatechars(self.title, 100)

    @property
    def content_short(self):
        return truncatechars(striptags(self.content), 220)

news/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.utils.translation import gettext as _
from django.template.defaultfilters import striptags, truncatechars

from .models import News

# Create your views here.
class NewsListView(ListView):
    template_name = 'news/news_list.html'
    context_object_name = 'news_queryset'

    def get_queryset(self):
        queryset = News.objects.filter(publish=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['meta_title'] = _('news').capitalize()
        context['meta_robots'] = 'index, follow'
        return context

def news_detail(request, id):
    news = get_object_or_404(News, id=id)

    # Facebook comments are embedded in URI. We have [/en, /th] (called i18n pattern) to
    # separate each language of all pages. However, we want comments of all languages to
    # stay together. Therefore, we have to remove i18n pattern from the URI.
    locator = request.get_full_path()
    fb_href = request.build_absolute_uri(locator[3:])

    return render(request, 'news/news_detail.html', {
        'news': news,
        'meta_title': truncatechars(news.title, 100),
        'meta_desc': truncatechars(striptags(news.content), 200),
        'meta_img': request.build_absolute_uri(news.image.url),
        'meta_robots': 'index, nofollow',
        'data_href': fb_href,
    })

def news_list(request, qty):
    news = News.objects.filter(publish=True)[:qty]
    return news

news/templates/news/news_detail.html
{% extends 'base.html' %}
{% load static i18n %}

{% block sdk %}
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v5.0&appId=1202114269848936&autoLogAppEvents=1"></script>
{% endblock sdk %}

{% block content %}
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="text-center">
                    <img src="{{news.image.url}}" class="img-fluid">
                </div>
                <br>
                <h2>{{news.title}}</h2>
                <div class="news-content">{{news.content|safe}}</div>
                <br>

                <div class="fb-comments" data-href="{{data_href}}" data-width="100%" data-numposts="5"></div>
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/news_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    <br>
    <div class="container">
        <h3 class="text-center text-capitalize">{% trans 'news' %}</h3>
        <br>

        {% include 'news/row_news.html' %}
    </div>
{% endblock %}

news/templates/news/row_news.html
{% load static i18n %}

<div class="row justify-content-center row-card news">
    {% for news_query in news_queryset %}
        <div class="col-md-6 col-card">
            <a href="{% url 'news:news-detail' id=news_query.id %}" class="card text-dark" target="_blank">
                <div class="card-body">
                    <div class="card-img h45" style="background-image:url('{{news_query.image.url}}')"></div>
                    <div class="card-text">
                        <h5>{{news_query.title_short|safe}}</h5>
                        <span>{{news_query.content_short|safe}}</span>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
</div>