pcj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView

from finance.views import finance_view

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('finance/', include('finance.urls')),
    path('news/', include('news.urls')),
    path('', include('page.urls')),
    path('product/', include('product.urls')),
    path('project/', include('project.urls')),

    path('webmail/', RedirectView.as_view(url='https://www.pcjindustries.co.th:2096/')),
    path('whm/', RedirectView.as_view(url='https://www.pcjindustries.co.th:2087/')),

    # legacy path for this url 'index.php?tpid=0031&pgname=finance&count=1'
    path('index.php/', finance_view, name='finance-view-2'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from .views import (
    ProjectListView,
    project_detail,
)

app_name = 'project'
urlpatterns = [
    path('', ProjectListView.as_view(), name='project-list'),
    path('<int:id>/', project_detail, name='project-detail'),
]

project/models.py
from django.db import models
from django.utils.translation import get_language

# Create your models here.
class Project(models.Model):
    title_en    = models.CharField(max_length=255, verbose_name='title english')
    title_th    = models.CharField(max_length=255, blank=True, verbose_name='title thai')
    country     = models.CharField(max_length=255)
    area        = models.CharField(max_length=255)
    year        = models.CharField(max_length=10)
    company     = models.CharField(max_length=255, blank=True)
    image       = models.ImageField(upload_to='project')
    order       = models.PositiveIntegerField(default=0, blank=False, null=False)

    @property
    def title(self):
        return self.title_th if get_language()=='th' and self.title_th else self.title_en

    class Meta:
        ordering = ('-order',)

    def __str__(self):
        return self.title_en

project/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.Form):
    country = forms.ChoiceField()
    year = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        projects = Project.objects.all()
        # c = kwargs['initial']['country']
        # y = kwargs['initial']['year']

        # if c and c != 'all':
        #     projects = projects.filter(country=c)
        # if y and y != 'all':
        #     projects = projects.filter(year=y)

        # Distinct for SQLite is not supported
        # Therefore, have to implement distinct value manually
        countries = set()
        years = set()

        for p in projects:
            countries.add((p.country, p.country))
            years.add((p.year, p.year))

        countries = list(countries)
        years = list(years)

        # Sort ascending order
        countries.sort()
        years.sort()

        countries.insert(0, ('all', 'all'))
        years.insert(0, ('all', 'all'))

        self.fields['country'].choices = countries
        self.fields['year'].choices = years

project/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic.edit import FormMixin
from django.http import JsonResponse
from django.utils.translation import get_language
from django.core.paginator import Paginator
from django.utils.translation import gettext as _

from .models import Project
from .forms import ProjectForm

# Create your views here.
class ProjectListView(FormMixin, ListView):
    template_name = 'project/project_list.html'
    context_object_name = 'project_queryset'
    form_class = ProjectForm

    def get_initial(self):
        return {
            'country': self.request.GET.get('country'),
            'year': self.request.GET.get('year'),
        }

    def get_queryset(self):
        queryset = Project.objects.all()
        year = self.request.GET.get('year')
        country = self.request.GET.get('country')

        if year and year != 'all':
            queryset = queryset.filter(year=year)

        if country and country != 'all':
            queryset = queryset.filter(country=country)

        paginator = Paginator(queryset, 15)
        page = self.request.GET.get('page')
        queryset = paginator.get_page(page)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['meta_title'] = _('projects').capitalize()
        context['meta_robots'] = 'index, nofollow'
        return context

def project_detail(request, id):
        project = Project.objects.filter(id=id)
        p = project.first()
        values = {}

        if p:
            values = project.values().first()
            values['title'] = p.title
            values['image'] = p.image.url
            del values['title_en']
            del values['title_th']
            del values['order']

        return JsonResponse(values)

def project_list(request, qty):
    projects = Project.objects.all()[:qty]
    return projects

project/templates/project/project_list.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{% block content %}
    <br>
    <div class="container">
        <h3 class="text-center text-capitalize">{% trans 'projects' %}</h3>

        <form action="{% url 'project:project-list' %}" method="GET" class="form-inline text-capitalize">
            <label>{% trans 'filter-by' %} &nbsp;&nbsp;</label>

            {{ form.country|add_label_class:'mr-1'}}
            {{ form.country|add_class:'form-control text-capitalize mr-sm-3 mb-2 mb-sm-0' }}

            {{ form.year|add_label_class:'mr-1'}}
            {{ form.year|add_class:'form-control text-capitalize mr-sm-3 mb-2 mb-sm-0' }}

            <input type="submit" value="{% trans 'select' %}" class="btn btn-outline-primary text-capitalize mt-2 mt-sm-0">
        </form>
        <hr>

        {% include 'project/row_project.html' %}
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/projectModal.js' %}"></script>
    <script src="{% static 'js/projectForm.js' %}"></script>
{% endblock extra_js %}

project/templates/project/row_project.html
{% load static i18n %}

<div class="row row-card project">
    {% for project_query in project_queryset %}
        <div class="col-md-4 col-card">
            <a href="{% url 'project:project-detail' id=project_query.id %}" class="card card-label card-project" data-toggle="modal" data-target="#modalCenter">
                <div class="card-img h45" style="background-image:url('{{project_query.image.url}}')"></div>
                <div class="card-text">{{project_query.title}}</div>
            </a>
        </div>
    {% endfor %}
</div>

{% if project_queryset.has_other_pages %}
    <div class="text-center">
        Page&nbsp;
        <select name="page" id="page" class="form-control" style="width: inherit; display: inline-block;">
            {% for p in project_queryset.paginator.page_range %}
                <option value="{{p}}" {%if p == project_queryset.number %} selected {% endif %} >{{p}}</option>
            {% endfor %}
        </select>
    </div>
{% endif %}



<div class="modal fade" id="modalCenter" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title w-100 text-center text-capitalize" id="modalTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span></span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row justify-content-center">
                    <img src="" class="img-fluid" id="modalImg">
                </div>
                <div class="row justify-content-center">
                    <table class="text-capitalize">
                        <tr>
                            <td><strong>{% trans 'area' %}</strong></td><td id="modalAddress"></td>
                        </tr>
                        <tr>
                            <td><strong>{% trans 'company' %}</strong></td><td id="modalCompany"></td>
                        </tr>
                        <tr>
                            <td><strong>{% trans 'year' %}</strong></td><td id="modalYear"></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>