page/urls.py
from django.urls import path
from .views import *

app_name = 'page'
urlpatterns = [
    path('', page_home, name='page-home'),
    path('about/', page_about, name='page-about'),
    path('contact/', page_contact, name='page-contact'),
    path('career/', page_career, name='page-career'),
]

pcj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView

from finance.views import finance_view

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('finance/', include('finance.urls')),
    path('news/', include('news.urls')),
    path('', include('page.urls')),
    path('product/', include('product.urls')),
    path('project/', include('project.urls')),

    path('webmail/', RedirectView.as_view(url='https://www.pcjindustries.co.th:2096/')),
    path('whm/', RedirectView.as_view(url='https://www.pcjindustries.co.th:2087/')),

    # legacy path for this url 'index.php?tpid=0031&pgname=finance&count=1'
    path('index.php/', finance_view, name='finance-view-2'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static sass_tags alter_lang_uri i18n %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>

        <!-- Meta Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1582338805915354');
        fbq('track', 'PageView');
        </script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=1582338805915354&ev=PageView&noscript=1"
        /></noscript>
        <!-- End Meta Pixel Code -->

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-84010436-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'UA-84010436-1');
        </script>

        <!-- Global site tag (gtag.js) - Google Ads: 672174391 -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=AW-672174391"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'AW-672174391');
        </script>

        <!-- Event snippet for con conversion page -->
        <script>
          gtag('event', 'conversion', {'send_to': 'AW-672174391/1RZECLO94sMBELeiwsAC'});
        </script>

        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1/css/bootstrap-grid.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1/css/bootstrap-reboot.css' %}">
        <link rel="stylesheet" href="{% static 'scss/fonts.css' %}">
        <link rel="stylesheet" href="{% sass_src 'scss/base4.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'scss/yamm.scss' %}">

        <meta name="google-site-verification" content="K57hywJun3eBmrh-bGSSVHgBKAzE8VnzN2srLagNkJo" />

        <title>{{meta_title}}</title>
        <meta name="author"             content="{% trans 'pcj-industries-full' %}">
        <meta name="description"        content="{{meta_desc}}" />
        <meta name="keywords"           content="{{meta_kw}}" />
        <meta name="robots"             content="{{meta_robots}}" />
        <meta name="googlebot"          content="{{meta_robots}}" />

        <meta property="og:url"         content="{{request.build_absolute_uri}}" />
        <meta property="og:type"        content="website" />
        <meta property="og:title"       content="{{meta_title}}" />
        <meta property="og:description" content="{{meta_desc}}" />
        <meta property="og:image"       content="{{meta_img}}" />

        <link rel="alternate" href="{% alter_lang_uri request 'en' %}" hreflang="en" />
        <link rel="alternate" href="{% alter_lang_uri request 'th' %}" hreflang="th" />
    </head>
    <body>
        {% block sdk %}
        {% endblock sdk %}

        {% include 'navbar.html' %}

        {% block content %}
        {% endblock content %}

        {% include 'footer.html' %}

        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'bootstrap-4.3.1/js/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'js/toggleDropdown.js' %}"></script>

        {% block extra_js %}
        {% endblock extra_js %}
    </body>
</html>

templates/footer.html
{% load static i18n %}

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-8 text-center text-md-left">
                <div>
                    <div class="avoid-wrap">
                        <span class="icon-phone-alt"></span>
                        {% if LANG == 'en' %}
                            <a href="tel:{{PHONE1_en}}">{{PHONE1_en}}</a>,&nbsp;
                            <a href="tel:{{PHONE2_en}}">{{PHONE2_en}}</a>
                        {% else %}
                            <a href="tel:{{PHONE1_th}}">{{PHONE1_th}}</a>,&nbsp;
                            <a href="tel:{{PHONE2_th}}">{{PHONE2_th}}</a>
                        {% endif %}
                        &nbsp;
                    </div>
                    <div class="avoid-wrap">
                        <span class="icon-envelope"></span>
                        <a href="mailto:{{EMAIL_SALES}}">{{EMAIL_SALES}}</a>
                    </div>
                </div>
                <div style="padding-top: 0.5em;">Copyright © 2002-{% now "Y" %} All Rights Reserved.</div>
                <div>PCJ INDUSTRIES CO., LTD.</div>
            </div>
            <div class="col-md-4 text-capitalize text-right text-center text-md-right">
                <span class="follow-us">{% trans 'follow-us' %}</span>
                <a href="{{FACEBOOK}}" class="sub-button" target="_blank"><span class="icon-facebook-f"></span></a>
                <a href="{{YOUTUBE}}" class="sub-button" target="_blank"><span class="icon-youtube"></span></a>
            </div>
        </div>
    </div>
</footer>

templates/navbar.html
{% load static i18n %}

<nav class="yamm navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'page:page-home' %}">
            <img src="{% static 'images/pcj-logo-full-'|add:LANG|add:'-2.jpg' %}" class="d-none d-lg-block">
            <img src="{% static 'images/pcj-logo.jpg' %}" class="d-lg-none">
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
            <span class="icon-bar top-bar"></span>
            <span class="icon-bar middle-bar"></span>
            <span class="icon-bar bottom-bar"></span>
        </button>
        <div id="navbarNavDropdown" class="navbar-collapse collapse">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav">
                {% for navbar_item in navbar_items %}
                    {% if navbar_item.0 == 'products' %}
                        <li class="nav-item dropdown yamm-fw">
                            <a class="nav-link text-dark text-uppercase dropdown-toggle" href="{{navbar_item.1}}" data-toggle="dropdown">
                                {% trans navbar_item.0 %}
                            </a>
                            <div class="dropdown-menu collapse" id="collapseDropdown">
                                {% include 'product/row_product.html' %}
                            </div>
                        </li>
                    {% elif navbar_item.0 in 'en,th' %}
                        <li class="nav-item">
                            <a class="nav-link text-dark text-uppercase" href="{{navbar_item.1}}" style="margin: -2px;">
                                <img src="{% static navbar_item.2 %}">
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-dark text-uppercase" href="{{navbar_item.1}}">{% trans navbar_item.0 %}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>

templates/tab.html
{% load static i18n %}

{% for doc in docs.items %}
    {% if doc.1 %}
        <h3 class="text-center text-capitalize">{% trans doc.0 %}</h3>
        <div class="row justify-content-center">
            <div class="col-md-10 section-document">
                <div class="row">
                    {% for item in doc.1 %}
                    <a class="card" href="{{item.doc.url}}" target="_blank">
                        <div class="frame">
                            {% if item.image %}
                            <img src="{{item.image.url}}">
                            {% else %}
                            <img src="{% static 'images/document.jpg' %}">
                            {% endif %}
                        </div>
                        <h6>{{item.title}}</h6>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <hr>
    {% endif %}
{% endfor %}